apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-react-app-deployment
  labels:
    app: my-react-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-react-app
  template:
    metadata:
      labels:
        app: my-react-app
    spec:
      containers:
      - name: my-react-app
        image: 381491873314.dkr.ecr.us-east-1.amazonaws.com/java_images:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
