name: ReactJsWorkflow
on: [push, workflow_dispatch ]
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
    - name: Clone the repo
      uses: actions/checkout@v4
    - name: Install Node Js
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Install Dependincies
      run: npm install
    - name: Creating the Build
      run: npm run build
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
    - name: Login to ECR
      uses: docker/login-action@v3
      with:
          registry: 381491873314.dkr.ecr.us-east-1.amazonaws.com
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}    
      
